### ISSUE TITLE
Auth über mehrere Geräte

### ISSUE THREAD

**Issue by eazyliving** [eazyliving/fyyd-api#1]
Aktuell kann man nur ein Gerät für eine App autorisieren. Möchte man eine App auf mehreren Geräten nutzen, erfolgt jedes Mal eine neue Autorisation, die vorherige auf einem anderen Gerät wird dadurch ungültig.

Der Fehler ist nicht eben trivial, muss aber behoben werden.

**Comment by funkenstrahlen** [comment]
Funktioniert jetzt

**Comment by funkenstrahlen** [comment]
Kannst du schließen.
