### ISSUE TITLE
Feature Request: Nach User suchen

### ISSUE THREAD

**Issue by funkenstrahlen** [eazyliving/fyyd-api#10]
Ich würde gerne eine Suche nach einem User einbauen. Das würde bedeuten nach nick und nach fullname Suchen zu können wäre nötig.

Idee dahinter: Ich will zum Beispiel alle Kurationen von eazy sehen.

**Comment by eazyliving** [comment]
Die Idee dahinter ist vermutlich nicht gut formuliert. Wenn Du den eazy hast, dann kannst Du diese Infos ja besorgen. Ich vermute, Du möchtest etwas wie /search/user?nick=eazy oder ?fullname=stefan und dann eine Liste aller möglichen Hits. Oder?

**Comment by funkenstrahlen** [comment]
> Ich vermute, Du möchtest etwas wie /search/user?nick=eazy oder ?fullname=stefan und dann eine Liste aller möglichen Hits. Oder?

Ja genau so was in die Richtung. Am besten recht allgemein gehalten die Suche, so dass man als User einfach nur einen Namen wie „Tim Pritlove“ eingeben kann und dann dessen User und darüber dann seine Kurstionen findet.

**Comment by eazyliving** [comment]
erledigt. /search/user seit heute Nacht in der API enthalten (siehe Doku)
