### ISSUE TITLE
Coverart der Episode automatisch auf Podcast Coverart linken?

### ISSUE THREAD

**Issue by funkenstrahlen** [eazyliving/fyyd-api#13]
Ich zeige in Skoon aktuell Coverarts zu den Episoden an. Dazu brauche ich allerdings drei Requests pro Coverart:

* Episode laden
* Passenden Podcast laden
* Coverart laden

Aktuell ist das so gelöst, dass das Episoden Coverart in der API leer ist, wenn der Podcast selbst da im Feed nichts hinterlegt hat.

Vorschlag: Die API wirft als Coverart für die Episode automatisch das Podcast Coverart aus, wenn kein eigenes für die Episode gesetzt ist.

Das würde auf Clientseite einen Request sparen und wäre wesentlich performanter.

**Comment by eazyliving** [comment]
Erledigt :)

**Comment by funkenstrahlen** [comment]
Wunderbar! Danke!
