### ISSUE TITLE
Link to FyydKit repository: A Swift implementation of the fyyd API

### ISSUE THREAD

**Issue by funkenstrahlen** [eazyliving/fyyd-api#14]
Hier wird das in Zukunft entstehen:

https://github.com/funkenstrahlen/FyydKit

**Comment by eazyliving** [comment]
Soll ich das denn nun schon in die Doku aufnehmen? Mache ich mehr als nur gerne, aber mir ist noch nicht ganz klar, ob Du das schon wünschst :-)

**Comment by funkenstrahlen** [comment]
Klar kannst du gerne machen. Ist zwar bei weitem noch nicht fertig, aber das wird...

**Comment by eazyliving** [comment]
Hab ein Kapitel über Interfaces hinzugefügt.
