### ISSUE TITLE
Discover Hot Podcasts

### ISSUE THREAD

**Issue by christophwolff** [eazyliving/fyyd-api#19]
Would be nice to have this in the API

**Comment by eazyliving** [comment]
Here we ware:

https://api.fyyd.de/0.2/feature/hot

Please keep in mind: this is calculated dynamically - at them moment of writing this :)
It could take a few seconds for the response. I'll change this to statically data in a few days so responses will drop in duration.

Secondly: Hot is not the same as "charts". This covers podcasts where there's the most activity detected the last days (8). If this would be charts, WRINT would have a fixed place at no 1 ;)

**Comment by christophwolff** [comment]
Nice! Thx!

The first Podcast seems to have issues with the absolute image URLs

```JavaScript
layoutImageURL: "/images/na300.png",
thumbImageURL: "/images/na80.png",
smallImageURL: "/images/na150.png",
microImageURL: "/images/na20.png",

```

**Comment by eazyliving** [comment]
fixed (hopefully :))

**Comment by yalematta** [comment]
I am requesting with count = 30 everytime I hit the following API: https://api.fyyd.de/0.2/feature/podcast/hot?count=30&language=en} but it returns no response. 
Using count = 12 returns data, count = 13 does not.

**Comment by eazyliving** [comment]
Seems to be fixed.
