### ISSUE TITLE
Problem mit Coverart Upload via Multipart Form Data

### ISSUE THREAD

**Issue by funkenstrahlen** [eazyliving/fyyd-api#22]
Wenn ich aktuell ein coverart an `/curation` sende mit einem multipart form request, dann bekomme ich keinen Fehler zurück.

Das hochgeladene Bild wird nicht übernommen. Auch gibt der Request nicht die Curation als JSON zurück, sondern einfach nur nichts.

**Comment by funkenstrahlen** [comment]
Interesting. I just realized the issue only occurs on iPad. But not on iPhone. So maybe the iPad upload actually causes a problem in the backend but it does not return an error response?

**Comment by funkenstrahlen** [comment]
Es ist auf jeden Fall mein Bier zu schauen was da auf dem iPad falsch läuft. Allerdings sollte dann der Server mit Fehler antworten wenn was schief läuft.

**Comment by eazyliving** [comment]
Kannst Du mir die ID der curation nennen? Dann schau ich mal, was die Logs hergeben.

**Comment by funkenstrahlen** [comment]
@eazyliving Zum Beispiel `2984`

**Comment by eazyliving** [comment]
Was ich sehen kann (und das ist nicht viel), ist der Umstand, dass schlicht keine Datei ankommt bzw. erkannt wird. Jetzt bräuchte ich mal ein iPad ;)

**Comment by funkenstrahlen** [comment]
@eazyliving Das ist ein guter Hinweis dafür, dass ich das fixen muss. Aber das war mir vorher klar, dass ich da ein Problem habe. Ich würde nur gerne wissen, warum die API in dem Fall keinen Fehler liefert.

**Comment by eazyliving** [comment]
Weil ich da einen Fehler nicht abfange. Das Skript dahinter schmiert schlicht ab. Ich korrigiere das gerade.

**Comment by funkenstrahlen** [comment]
> Weil ich da einen Fehler nicht abfange. Das Skript dahinter schmiert schlicht ab. Ich korrigiere das gerade.

Super! Mehr brauchst du gar nicht machen :) Der Rest ist meine Baustelle 🙈

**Comment by eazyliving** [comment]
Ich kann's nur nicht gut testen, ob ich den Fehler wirklich korrekt abfange. Ich hab übrigens mal forensic angeschaltet. Mal sehen, was das ausspuckt.

**Comment by eazyliving** [comment]
Bug gefunden, Bug behoben. Vielen Dank, Stefan für's Finden :)
