### ISSUE TITLE
Bug: API endpoint for fetching podcasts does list category IDs as Strings

### ISSUE THREAD

**Issue by funkenstrahlen** [eazyliving/fyyd-api#24]
I discovered the JSON for `curation` and `podcast` handles categories differently. A curation does list `categories` as an array if Integers in the JSON. A podcast does list its `categories` as an array of Strings though.

This currently breaks decoding podcast JSON in my client.

**Comment by eazyliving** [comment]
My fault. Fixed!

**Comment by funkenstrahlen** [comment]
Thanks 😍
