### ISSUE TITLE
Feature request: Podcasts einer bestimmten Kategorie abrufen

### ISSUE THREAD

**Issue by funkenstrahlen** [eazyliving/fyyd-api#4]
Das wäre am einfachsten möglich, wenn `/search/podcast` einen Parameter `category_id` bekommt?

Ich würde gerne die Möglichkeit einbauen, dass man auch Podcast nach Kategorien durchstöbern kann.

**Comment by eazyliving** [comment]
Ich nehme an du meinst category_id :)
Was stimmt mit [GET /category] nicht?

**Comment by funkenstrahlen** [comment]
> Ich nehme an du meinst category_id :)

Oh natürlich. Habe ich oben korrigiert.

> Was stimmt mit [GET /category] nicht?

Oh das habe ich komplett übersehen! Das kann ich dafür natürlich verwenden.

Abgesehen davon wäre es aber vielleicht trotzdem nicht schlecht, wenn die Suche nach Podcasts einen Kategorie Filter bekäme. Aber dafür hätte ich dann nicht sofort einen Nutzen.
