### ISSUE TITLE
Feature Request: Kategorie einer Kuration manuell festlegen

### ISSUE THREAD

**Issue by funkenstrahlen** [eazyliving/fyyd-api#5]
Darüber hatten wir schon mal gesprochen. Ich schreibe das hier nur mal auf, damit es nicht verloren geht :)

**Comment by eazyliving** [comment]
Ach herrje, das müsste ich nun wirklich mal angehen. Der Einfachheit halber erst mal nur per API, danach im Web.

**Comment by eazyliving** [comment]
Ich bin jetzt grad ein wenig verloren. Was würde ich denn da sinnvollerweise erwarten? Ein JSON-Array der Category IDs oder ein kommaseparierter String mit den IDs?

**Comment by eazyliving** [comment]
Fixed: https://github.com/eazyliving/fyyd-api/blob/master/README.md#post-curation
