### ISSUE TITLE
Feature request: Kommentar des Authors zur Episode zeigen

### ISSUE THREAD

**Issue by funkenstrahlen** [eazyliving/fyyd-api#6]
Ich würde gerne zu Episoden einer Kuration auch den Kommentar des Authors anzeigen (sofern er denn eine `why` Nachricht hinterlassen hat.

**Comment by eazyliving** [comment]
Ist jetzt enthalten. Schlüssel: "why" (don't ask why... ;-))

**Comment by funkenstrahlen** [comment]
Ich nehme mal an das ist ein String. Ist der leer der `nil`, wenn nichts eingetragen wurde?
