### ISSUE TITLE
Chaching Problem: Thumbnails sollten immer neuen zufälligen Namen bekommen

### ISSUE THREAD

**Issue by funkenstrahlen** [eazyliving/fyyd-api#9]
Da hatten wir ja schon längere Gespräche drüber. Das Problem ist nicht wirklich kritisch, besteht aber weiterhin und sorgt öfter für Irritation.

Wenn Coverarts sich ändern, dann bleibt die URL zum Bild gleich und iOS invalidiert den Cache nicht. Damit dauert es meist Tage bis Skoon das neue Coverart anzeigt, obwohl es auf dem Server schon getauscht ist.

Ich kann leider in iOS nicht am System Cache vorbei implementieren und würde das auch ungern tun, denn der tut in der Regel schon das Richtige.

Leider funktioniert die bisherige Lösung mit dem zusätzlich angehängten URL Parameter unter iOS nicht.

Mir ist unklar wie Podcat bisher damit umgeht?

Am besten wäre es, wenn der Dateiname aller Bilder in der API ein langer zufälliger String ist. `ajwh4kgjh354tkdjfg.png` zum Beispiel. Der ändert sich dann immer, wenn sich das Bild ändert.

Vorteil: Du kannst auf dem Server sogar unendliche Cachezeit für den Client vorschlagen. Damit verringern sich die Requests auf den Server deutlich.

**Comment by eazyliving** [comment]
Wenn die Penunzen ausreichen (haha), dann wird das Image-System auf einen eigenen Server ausgelagert. In dem Zuge werde ich das Thema dann angehen, vorher lohnt sich das nicht.

**Comment by eazyliving** [comment]
So, nun wird's mal wieder Zeit, ein wenig Liebe in Richtung API zu werfen. Dieses Ding hier ist ja eigtl schon erledigt, oder?

**Comment by funkenstrahlen** [comment]
Soll ich das nochmal testen? Ich habe das lange nicht geprüft, da ich von dir nichts gehört habe. Aber wenn du das jetzt neu gebaut hast, kannst du das ja auch einfach schließen hier.

**Comment by eazyliving** [comment]
Stimmt auch wieder!
